### ISSUE TITLE
Redis_1 |13:C 21 July 18:51:12:13.067 * RDB 6 MB of memory used by copy-on-write

### ISSUE THREAD

**Issue by satishparimi** [Fuzzapi/fuzzapi#58]
Setup FuzzAPI Tool
The same process is going to execute by number time when i execute
![image](https://user-images.githubusercontent.com/30291342/28477968-032ca244-6e74-11e7-80e1-5ac34a5a1879.png)

the error is : same PID is executing no of times as like 
![image](https://user-images.githubusercontent.com/30291342/28477994-1efe60d4-6e74-11e7-8306-11bd9706a85a.png)

**Comment by satishparimi** [comment]
Can any one fix this issue, my Test Env is 
OS: Windows 10
Ruby installed: 2.4.1
And me using docker to setup FuzzAPI Tool for API Pen Testing

**Comment by abhijeth** [comment]
This is strange. Never seen this issue. Thanks for bringing this up.

**Comment by satishparimi** [comment]
Hi Abhijeth thanks for your reply,

actaully me tried to install FuzzAPI in windows -7 machine also with direct work flow like
    1) bundle install....

but me getting issue like your ruby version is 2.4.2 and gem file version is 2.3.0 seems it like versioning problem while setting up FuzzAPI Tool.

if possible can you please publish latest fiiles in GitHub.

Thanks in advance.

**Comment by abhijeth** [comment]
@lalithr95 just confirmed that these are latest. Will ask him to look again.

**Comment by satishparimi** [comment]
Thanks abhijeth
if possible will you guys just confirm comparability with Win-10 or 07. that would be helpful actually.

**Comment by abhijeth** [comment]
Windows 07 mate.
