### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mboelen** [Fuzzapi/fuzzapi#59]
While researching this tool for our [Linux security tools](https://linuxsecurity.expert/security-tools/) section, I couldn't find the license for this project. Where is it located?

**Comment by lalithr95** [comment]
@mboelen I have recently added MIT license for this tool, you can find it [here](https://github.com/Fuzzapi/fuzzapi/blob/master/LICENSE).

**Comment by mboelen** [comment]
Thanks!
