### ISSUE TITLE
Error: Older version of Bundler

### ISSUE THREAD

**Issue by hacksingh** [Fuzzapi/fuzzapi#62]
I am getting the below error when I try to do "Bundle install". I already tried `gem install bundler`.

Thanks.

root@kali:~/fuzzapi/bin# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed,
and installing your bundle as root will break this application for all
non-root users on this machine.
Warning: the running version of Bundler (1.13.6) is older than the version that created the lockfile (1.15.0). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.3.3, but your Gemfile specified 2.3.0

**Comment by abhijeth** [comment]
Did you try installing it using docker?

**Comment by lalithr95** [comment]
@hacksingh that's just a warning, you can ignore it. Reopen issue if you find a bug related to it.

**Comment by hacksingh** [comment]
Thanks for replying but the command "bundle install" never ran. Although this is a warning the bundle never completed.
I even tried the below commands:
sudo apt-get install libpq-dev

**Comment by hacksingh** [comment]
@lalithr95 I cannot re-open my own issues if a repo collaborator closed them

**Comment by lalithr95** [comment]
Do you have the trace for the error ? or any screenshot where bundle install was not successful.
