### ISSUE TITLE
Unable to install - Fuzzapi

### ISSUE THREAD

**Issue by Kantha4security** [Fuzzapi/fuzzapi#64]
Hello,

I'm not able to install Fuzzapi on Kali Linux.

I'm getting below errors

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/rake-11.3.0.gem. It may be corrupted.
Using i18n 0.7.0
Using json 1.8.3

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/minitest-5.9.1.gem. It may be corrupted.
Using thread_safe 0.3.5
Using addressable 2.4.0
Using unf_ext 0.0.7.2
Using http-form_data 1.0.1
Using http_parser.rb 0.6.0
Using builder 3.2.2
Using erubis 2.7.0

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/mini_portile2-2.1.0.gem. It may be corrupted.
Using rack 1.6.4

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/mime-types-data-3.2016.0521.gem. It may be corrupted.
Using arel 6.0.3
Using bundler 1.12.5
Using thor 0.19.1

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/concurrent-ruby-1.0.2.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/execjs-2.7.0.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/bcrypt-3.1.11.gem. It may be corrupted.
Using debug_inspector 0.0.2

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/sass-3.4.22.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/byebug-9.0.5.gem. It may be corrupted.
Using coffee-script-source 1.10.0

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/connection_pool-2.2.0.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/orm_adapter-0.5.0.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/devise-bootstrap-views-0.0.9.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/multi_json-1.12.1.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/newrelic_rpm-3.15.2.317.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/pg-0.18.4.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/puma-3.4.0.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/rails-assets-tether-1.3.7.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/redis-3.3.1.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/tilt-2.0.5.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/spring-1.7.2.gem. It may be corrupted.
Using sqlite3 1.3.11

Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/turbolinks-source-5.0.0.gem. It may be corrupted.
An error occurred while installing rake (11.3.0), and Bundler cannot continue.
Make sure that `gem install rake -v '11.3.0'` succeeds before bundling.

**Comment by abhijeth** [comment]
Hi,

As your error says "Make sure that gem install rake -v '11.3.0' succeeds before bundling." 

Alternatively, try using https://www.youtube.com/watch?v=0lV2AlO1HMo

**Comment by abhijeth** [comment]
Closing due to no response.
