### ISSUE TITLE
"GET /ping" inserts vulnerability in running scan

### ISSUE THREAD

**Issue by sectest667** [Fuzzapi/fuzzapi#74]
Hi,
just saw that if you try to get the status for a running scan, eg scan number 7 by doing
`GET /ping/7`

a XXE vulnerability is inserted into the scan results:
```
Started GET "/ping/7" for 172.18.0.1 at 2018-02-01 16:43:40 +0000
Processing by PingController#index as HTML
  Parameters: {"id"=>"7"}
  Scan Load (0.3ms)SELECT  "scans".* FROM "scans" WHERE "scans"."id" = ? LIMIT 1  [["id", 7]]
   (0.1ms)  begin transaction
  SQL (0.2ms)  INSERT INTO "vulnerabilities" ("status", "class_type", "description", "value", "scan_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?) [["status", "HIGH"], ["class_type", "Vulnerability"], ["description", "Possible XXE vulnerability in http://api.example.com/auth/oauth/token"], ["value", ""], ["scan_id", 7], ["created_at", "2018-02-01 16:43:40.550813"], ["updated_at", "2018-02-01 16:43:40.550813"]]
   (60.2ms) commit transaction
Completed 200 OK in 69ms (Views: 0.2ms | ActiveRecord: 60.8ms)
```

This does not look like it's intented...

Kind regards!

**Comment by lalithr95** [comment]
This is an intended behaviour and part of application design, When ever fuzzapi finds an XXE vulnerability, it uses ping endpoint to create a new vulnerability record. Note that it shouldn't create a vulnerability record when there is no XXE vulnerability in the testing application. If thats the case please reopen this issue. Thanks!

**Comment by sectest667** [comment]
Hi lalithr95,
thanks alort for the quick feedback.

Unfortunately my setup does not yet scan the target API, at least tcpdump does not show any outgoing packets.

This means that it does create a vulnerability record when it could not determine if there is a vulnerability.

Wondering why it seems to always insert a XXE entry, but hope I'll figure it out...

**Comment by sectest667** [comment]
Hi lalith95,
I can confirm that in my setup (see "Docker setup HOWTO") a
`ping/7`
adds a XXE vulnerability to the scan with the ID 7, even if the scan is already in status "completed".

I'd rate this as a bug then, though with severity "Low"...

Thanks for this tool and 
kind regards!
