### ISSUE TITLE
Error - Installation: Please fix this gemspec.

### ISSUE THREAD

**Issue by SleepyLctl** [Fuzzapi/fuzzapi#77]
Hi,

When I run:
`root@kali:~/Desktop/fuzzapi/Fuzzapi/bin# bundle install`

Then i get:
`Don't run Bundler as root.
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from https://rubygems.org/.......
You have one or more invalid gemspecs that need to be fixed.
The gemspec at /var/lib/gems/2.5.0/bundler/gems/API-fuzzer-26b60e42caa4/API_Fuzzer.gemspec is not valid. Please fix this gemspec.
The validation error was '"TODO: Put your gem's website or public repo URL here." is not a valid HTTP URI'`

I tried to play with it and fix it somehow, putting an address, but no success. I do not have exp with Ruby gems though. 

How to fix it? 
What should I put in? 

Thanks.

**Comment by SleepyLctl** [comment]
Well, I tried to redo the same on my testing Ubuntu and everything was working more less according to the Help. So it seems that my previous post is closely related to OS - Kali 2017.2

**Comment by jauharvp** [comment]
+1

**Comment by rnbwkat** [comment]
downgrade ruby to 2.3.0 and it will work fine.

**Comment by sivaarja** [comment]
solved by using `build update` instead fo `bundle install`

**Comment by tiowillians** [comment]
> solved by using `build update` instead fo `bundle install`

you mean: "bundle update"

Thanks a lot. It worked for me either.

**Comment by sivaarja** [comment]
> > solved by using `build update` instead fo `bundle install`
> 
> you mean: "bundle update"
> 
> Thanks a lot. It worked for me either.

yes it sorry for that, its "bundle" not "built"

**Comment by w4spy** [comment]
> solved by using `bundle update` instead fo `bundle install`

like a charm

**Comment by jauharvp** [comment]
I missed the comments, let me try!!
