### ISSUE TITLE
SocketError in ScansController#create 

### ISSUE THREAD

**Issue by jibz08** [Fuzzapi/fuzzapi#83]
getaddrinfo: Temporary failure in name resolution

  scan: @scan.id
    }
    ScanVulnerabilityWorker.perform_async(@scan.id, job_options)
    flash[:notice] = "Your scan is being processed"
    redirect_to scan_path(@scan)
  end

While i m running the scan , i m getting This error. 
Can i get help here.
![fuzzapi](https://user-images.githubusercontent.com/42267276/43949413-0b0e4902-9cab-11e8-96b2-ef104f72f1d8.JPG)

**Comment by lalithr95** [comment]
@jibz08 please make sure that you ran [step 6](https://github.com/Fuzzapi/fuzzapi#setup) correctly. If the issue still happens please re-open and comment on this issue.

**Comment by jibz08** [comment]
I Have checked The Same . Still I m facing the Same Issue. can i get some help here.
